name: Hunter
version: 1.0
author: AwesomeSauce
main: me.alpha.hunter.hunter
api-version: 1.8

depend: [Citizens]

commands:
  hunter:
    description: Core command for Hunter plugin! Do /hunter help for examples
    usage: /<command>
    aliases: huntr
  bot:
    description: Helps you create a Silent Bot!
    usage: /<command>
    aliases: gconfig